### ISSUE TITLE
1.3.38: XWPFConverterException: java.lang.NullPointerException: Cannot invoke "com.lowagie.text.pdf.PdfPRow.getCells()" because "row" is null

### ISSUE THREAD

**Issue by henricook** [LibrePDF/OpenPDF#1028]
**Describe the bug**

```
[info]     fr.opensagres.poi.xwpf.converter.core.XWPFConverterException: java.lang.NullPointerException: Cannot invoke "com.lowagie.text.pdf.PdfPRow.getCells()" because "row" is null
[info]     at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:71)
[info]     at fr.opensagres.poi.xwpf.converter.pdf.PdfConverter.doConvert(PdfConverter.java:39)
[info]     at fr.opensagres.poi.xwpf.converter.core.AbstractXWPFConverter.convert(AbstractXWPFConverter.java:42)
[info]     at myapp.template.services.docx.POIDocxGenerationServiceSpec$.toPdf(POIDocxGenerationServiceSpec.scala:2956)
[info]     at myapp.template.services.docx.POIDocxGenerationServiceSpec$MatchDocxMatcher.apply(POIDocxGenerationServiceSpec.scala:2871)
[info]     at myapp.template.services.docx.POIDocxGenerationServiceSpec$MatchDocxMatcher.apply(POIDocxGenerationServiceSpec.scala:2867)
[info]     at org.scalatest.matchers.should.Matchers$ShouldMethodHelperClass.shouldMatcher(Matchers.scala:7291)
[info]     at org.scalatest.matchers.should.Matchers$AnyShouldWrapper.should(Matchers.scala:7347)
[info]     at myapp.template.services.docx.POIDocxGenerationServiceSpec$$anon$72.<init>(POIDocxGenerationServiceSpec.scala:2750)
[info]     at myapp.template.services.docx.POIDocxGenerationServiceSpec.$anonfun$new$107(POIDocxGenerationServiceSpec.scala:2748)
[info]     ...
[info]     Cause: java.lang.NullPointerException: Cannot invoke "com.lowagie.text.pdf.PdfPRow.getCells()" because "row" is null
[info]     at com.lowagie.text.pdf.PdfPTable.redistributeRowspanHeight(PdfPTable.java:860)
[info]     at com.lowagie.text.pdf.PdfPTable.calculateHeights(PdfPTable.java:423)
[info]     at com.lowagie.text.pdf.ColumnText.goComposite(ColumnText.java:1364)
[info]     at com.lowagie.text.pdf.ColumnText.go(ColumnText.java:809)
[info]     at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocument.simulateText(StylableDocument.java:220)
[info]     at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocument.pageBreak(StylableDocument.java:160)
[info]     at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocument.columnBreak(StylableDocument.java:120)
[info]     at fr.opensagres.poi.xwpf.converter.pdf.internal.elements.StylableDocument.addElement(StylableDocument.java:101)
[info]     at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.endVisitTable(PdfMapper.java:1145)
[info]     at fr.opensagres.poi.xwpf.converter.pdf.internal.PdfMapper.endVisitTable(PdfMapper.java:123)
```

I believe this related to changes in https://github.com/LibrePDF/OpenPDF/pull/1027

**To Reproduce**
In this particular piece of Scala code I am converting a Docx to a PDF. This works on OpenPDF 1.3.36

```scala
  def toPdf(docx: Path): Path = {
    val tempFile = SingletonTemporaryFileCreator.create() // Empty file
    PdfConverter.getInstance()
      .convert(
        new XWPFDocument(GFiles.asByteSource(docx.toFile).openStream()),
        GFiles.asByteSink(tempFile).openStream(),
        PdfOptions.create()
          .fontProvider((familyName: String, _: String, size: Float, style: Int, color: Color) => { // <-- error occurs 'on this line' (likely in this block / in the converter's processing)
            Option(familyName).getOrElse("").split("\\s*,\\s*")
              .map(_.stripPrefix("\"").stripSuffix("\"").stripPrefix("'").stripSuffix("'"))
              .flatMap { family =>
                pdfFonts.collectFirst {
                  case (fd, baseFont) if fd.family.equalsIgnoreCase(family) =>
                    new Font(baseFont, size, style, color)
                }
              }.headOption.getOrElse {
                // Fall back to DejaVu Sans for any fonts that aren't found
                new Font(pdfFonts.find(_._1.family == "DejaVu Sans").get._2, size, style, color)
              }
          }),
      )
    tempFile
  }
```

**Expected behavior**
This should not throw a getCells is null error

**Screenshots**

**System (please complete the following information):**
 - Used Font:

**Additional context**

**Comment by andreasrosdal** [comment]
@fellmann Can you please investigate this bug?

**Comment by andreasrosdal** [comment]
NullPointerException here: https://github.com/LibrePDF/OpenPDF/blob/master/openpdf/src/main/java/com/lowagie/text/pdf/PdfPTable.java#L860

**Comment by andreasrosdal** [comment]
@henricook  Do you have any idea why the 'row' object is null there? Does this problem effect all Docx files you are converting to PDF, or only some specific files? Is there a table from Docx where there is a null row object?

**Comment by henricook** [comment]
Annoyingly I didn't write this code, I was just looking after the automatic update of the dependency! Is a `PTABLE` a literal visible table in the document, or is it a table structure that PDFs use for layout?

**Comment by andreasrosdal** [comment]
@henricook Are you able to create a pull request to solve this bug? Seems you have good test-data. If you create a pull request with a solution which prevents the NullPointerException, then I can create a new release of OpenPDF with the fix included.

**Comment by henricook** [comment]
I can put it on my list, I can't promise immediate action with work commitments at the moment. In the mean time please let me know if inspiration strikes

**Comment by fellmann** [comment]
I will provide a fix to check for null rows, although it's bad that this happens at all. Some code uses `table.getRows().set(i, null)` and similar for reasons I don't understand. NullPointerExceptions really are a big pain in Java.

**Comment by andreasrosdal** [comment]
I committed a fix for the NullPointerException in PdfTable.redistributeRowspanHeight() here, in order to understand this code better, also using ChatGPT. 
https://github.com/LibrePDF/OpenPDF/commit/beb9e511ba30f34b39aa9b9c8542efa466a965c5

Please let me know if this solves your problem in this case, and if there is a need to improve this code further. 
ChatGPT suggested rewriting the method using stream operations, which did make it look more modern, concise and readable.

I can create a new release of OpenPDF soon if this issue is solved now.

**Comment by andreasrosdal** [comment]
Can you please test using the latest master branch version of OpenPDF? @henricook

**Comment by andreasrosdal** [comment]
Thank you @fellmann

**Comment by henricook** [comment]
Thanks for such a speedy response both @andreasrosdal I'm sorry to ask, I'm a scala guy so I know how to do this with `sbt` and not much else, do you happen to have the (`mvn`?) commands I can use to deploy a local copy of OpenPDF (e.g. to ivy cache) that I can then import into my app?

**Comment by henricook** [comment]
Ignore me sorry, GPT to the rescue ;-)

**Comment by henricook** [comment]
Test now passes! Thanks again both! Good to release 1.3.39!

**Comment by andreasrosdal** [comment]
I will create a new release of OpenPDF this evening. If there is anything else you would like to see improved, now is the chance.
