### ISSUE TITLE
Build issue on OpenJDK 12

### ISSUE THREAD

**Issue by andreasrosdal** [LibrePDF/OpenPDF#154]
https://travis-ci.org/LibrePDF/OpenPDF/jobs/493210463

[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.lowagie.text.pdf.GlyphListTest
[INFO] Running com.lowagie.text.pdf.PdfNameTreeTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.lowagie.text.pdf.PdfNameTreeTest
[INFO] Running com.lowagie.text.pdf.core.document.PdfCrossReferenceTest
[ERROR] Tests run: 8, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.615 s <<< FAILURE! - in com.lowagie.text.pdf.core.document.PdfCrossReferenceTest
[ERROR] testPdfRepresentation  Time elapsed: 0.589 s  <<< ERROR!
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class java.io.OutputStream.
Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.
Java               : 12
JVM vendor name    : Oracle Corporation
JVM vendor version : 12+31
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 12+31
JVM info           : mixed mode, sharing
OS name            : Linux
OS version         : 4.4.0-101-generic
Underlying exception : java.lang.IllegalArgumentException: org.mockito.codegenOutputStream$MockitoMock$2006631203 must be defined in the same package as org.mockito.codegen.InjectionBase/package
	at com.lowagie.text.pdf.core.document.PdfCrossReferenceTest.testPdfRepresentation(PdfCrossReferenceTest.java:129)
Caused by: java.lang.IllegalArgumentException: org.mockito.codegenOutputStream$MockitoMock$2006631203 must be defined in the same package as org.mockito.codegen.InjectionBase/package
	at com.lowagie.text.pdf.core.document.PdfCrossReferenceTest.testPdfRepresentation(PdfCrossReferenceTest.java:129)
[INFO] Running com.lowagie.text.pdf.table.TableElementsAlignmentTest
[INFO] Tests run: 8, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 s - in com.lowagie.text.pdf.table.TableElementsAlignmentTest
[INFO] Running com.lowagie.text.pdf.fonts.FontTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.634 s - in com.lowagie.text.pdf.fonts.FontTest
[INFO] Running com.lowagie.text.pdf.SimplePdfTest
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 s - in com.lowagie.text.pdf.SimplePdfTest
[INFO] Running com.lowagie.text.ImageTest
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.098 s - in com.lowagie.text.ImageTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   PdfCrossReferenceTest.testPdfRepresentation:129 Mockito 
Mockito cannot mock t...
[INFO] 
[ERROR] Tests run: 39, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenPDF - Free and Open PDF ........................ SUCCESS [ 10.940 s]
[INFO] openpdf ............................................ FAILURE [ 23.560 s]
[INFO] pdf-xml ............................................ SKIPPED
[INFO] pdf-html ........................................... SKIPPED
[INFO] pdf-swing .......................................... SKIPPED
[INFO] pdf-toolbox ........................................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 52.936 s
[INFO] Finished at: 2019-02-14T12:24:10Z
[INFO] Final Memory: 37M/130M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project openpdf: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/travis/build/LibrePDF/OpenPDF/openpdf/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :openpdf
The command "mvn install -Dgpg.skip" failed and exited with 1

**Comment by andreasrosdal** [comment]
OpenJDK 12 now works.
