### ISSUE TITLE
acroFields.verifySignature throws ClassCastException

### ISSUE THREAD

**Issue by beat2** [LibrePDF/OpenPDF#160]
This is most probably an issue since the upgrade of BouncyCastle.

    PdfPKCS7 pdfPkcs7 = fields.verifySignature(signName);

Results in

```
java.lang.ClassCastException: org.bouncycastle.asn1.BERTaggedObject cannot be cast to org.bouncycastle.asn1.DERTaggedObject
	at com.lowagie.text.pdf.PdfPKCS7.<init>(PdfPKCS7.java:424)
	at com.lowagie.text.pdf.AcroFields.verifySignature(AcroFields.java:2270)
	at com.lowagie.text.pdf.AcroFields.verifySignature(AcroFields.java:2225)
	at com.lowagie.text.pdf.AcroFieldsTest.testVerifySignature(AcroFieldsTest.java:62)
```
Somewhat unrelated, does anybody have a code style formatter for eclipse?

**Comment by andreasrosdal** [comment]
Thanks!

**Comment by mkl-public** [comment]
The method `getObject` already is defined in the common parent class `ASN1TaggedObject` of `BERTaggedObject` and `DERTaggedObject`.

Thus, the simpler fix would have been to cast to `ASN1TaggedObject` instead of sometimes `BERTaggedObject` and sometimes `DERTaggedObject`.
