### ISSUE TITLE
Unbalanced save/restore state operators (in example PageNumbersWatermark)

### ISSUE THREAD

**Issue by bitkorn** [LibrePDF/OpenPDF#196]
The example throw an IllegalPdfSyntaxException:

```
com.lowagie.text.DocumentException: com.lowagie.text.exceptions.IllegalPdfSyntaxException: Unbalanced save/restore state operators.
	at com.lowagie.text.pdf.PdfDocument.add(PdfDocument.java:779)
	at com.lowagie.text.Document.add(Document.java:276)
	at de.bitkorn.openpdf.examples.directcontent.pageevents.PageNumbersWatermark.main(PageNumbersWatermark.java:71)
Caused by: com.lowagie.text.exceptions.IllegalPdfSyntaxException: Unbalanced save/restore state operators.
	at com.lowagie.text.pdf.PdfContentByte.sanityCheck(PdfContentByte.java:3145)
	at de.bitkorn.openpdf.examples.directcontent.pageevents.PageNumbersWatermark.onEndPage(PageNumbersWatermark.java:166)
	at com.lowagie.text.pdf.PdfDocument.newPage(PdfDocument.java:870)
	at com.lowagie.text.pdf.PdfDocument.carriageReturn(PdfDocument.java:1249)
	at com.lowagie.text.pdf.PdfDocument.add(PdfDocument.java:551)
	... 2 more
```

I am new to OpenPDF and can not debug this error.

My search in the www shows me that this is a very old bug from iText.

Can someone help me to learn?

**Comment by asturio** [comment]
@bitkorn Does the actual master-branch solves the problem for you?

**Comment by Zoharat** [comment]
I have OpenPDF version 1.3.26, and also get the same error.

**Comment by asturio** [comment]
Pull-requests are welcome!

**Comment by albfernandez** [comment]
> I have OpenPDF version 1.3.26, and also get the same error.

This concrete case was in the examplw file PageNumbersWatermark.java

Are you using PageNumbersWatermark.java or a different file?

**Comment by Zoharat** [comment]
So the font I used in my test I had the size accidentally set as 0. That caused this issue. Once I used a an actual non zero font it worked for me.
