### ISSUE TITLE
PageNumbersWatermark is broken

### ISSUE THREAD

**Issue by sixdouglas** [LibrePDF/OpenPDF#242]
The PageNumbersWatermark test  (com.lowagie.examples.directcontent.pageevents.PageNumbersWatermark) breaks with this exception:

```
com.lowagie.examples.directcontent.pageevents.PageNumbersWatermark
com.lowagie.text.DocumentException: com.lowagie.text.exceptions.IllegalPdfSyntaxException: Unbalanced save/restore state operators.
	at com.lowagie.text.pdf.PdfDocument.add(PdfDocument.java:775)
	at com.lowagie.text.Document.add(Document.java:276)
	at com.lowagie.examples.directcontent.pageevents.PageNumbersWatermark.main(PageNumbersWatermark.java:71)
Caused by: com.lowagie.text.exceptions.IllegalPdfSyntaxException: Unbalanced save/restore state operators.
	at com.lowagie.text.pdf.PdfContentByte.sanityCheck(PdfContentByte.java:3148)
	at com.lowagie.examples.directcontent.pageevents.PageNumbersWatermark.onEndPage(PageNumbersWatermark.java:166)
	at com.lowagie.text.pdf.PdfDocument.newPage(PdfDocument.java:866)
	at com.lowagie.text.pdf.PdfDocument.carriageReturn(PdfDocument.java:1245)
	at com.lowagie.text.pdf.PdfDocument.add(PdfDocument.java:547)
	... 2 more

```

**Comment by sixdouglas** [comment]
I went back in time (through the tags up to the 1.0.4) and failed to find a version where this test run without this stack trace.

Two options here:

* Remove the Sample
* Make the sample works

I prefer the second, but I don't feel able to do it.
