### ISSUE TITLE
AcroFields.setFieldProperty with NullPointerException start from v1.3.12

### ISSUE THREAD

**Issue by suiaing** [LibrePDF/OpenPDF#358]
Part of log using v1.3.15
java.lang.NullPointerException
	at com.lowagie.text.pdf.PdfContentByte.setGState(PdfContentByte.java:3042)
	at com.lowagie.text.pdf.PdfContentByte.saveColorFill(PdfContentByte.java:2350)
	at com.lowagie.text.pdf.PdfContentByte.setRGBColorFill(PdfContentByte.java:2233)
	at com.lowagie.text.pdf.PdfContentByte.setColorFill(PdfContentByte.java:2343)
	at com.lowagie.text.pdf.AcroFields.setFieldProperty(AcroFields.java:1066)

Within AcroFields.setFieldProperty:
PdfAppearance is created without PdfWriter
i.e. when saveColorFill, PdfContentByte.setGState is called and try to use the null writer

**Comment by suiaing** [comment]
Close as created pull request as #359
