### ISSUE TITLE
documentation - Provide clear explanation of correct version of Bouncy Castle to be used.

### ISSUE THREAD

**Issue by bigos** [LibrePDF/OpenPDF#465]
I am stuck at trying to sign my pdf.

And get a similar method error to this one:
https://stackoverflow.com/questions/43181550/nosuchmethoderror-org-bouncycastle-asn1-asn1inputstream-readobjectlorg-bouncyc

That explanation from 3 years ago says that bouncy castle needs a correct version to work. If they are correct please provide better documentation for that.

My error is:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.bouncycastle.asn1.ASN1OutputStream.writeObject(Lorg/bouncycastle/asn1/ASN1Primitive;)V
	at com.lowagie.text.pdf.PdfPKCS7.getEncodedPKCS7(PdfPKCS7.java:1344)
	at com.lowagie.text.pdf.PdfPKCS7.getEncodedPKCS7(PdfPKCS7.java:1204)
	at com.lowagie.text.pdf.PdfSigGenericPKCS.setSignInfo(PdfSigGenericPKCS.java:112)
	at com.lowagie.text.pdf.PdfSignatureAppearance.preClose(PdfSignatureAppearance.java:1075)
	at com.lowagie.text.pdf.PdfSignatureAppearance.preClose(PdfSignatureAppearance.java:967)
	at com.lowagie.text.pdf.PdfStamper.close(PdfStamper.java:249)
	at sal.Generator.signPdf(Generator.java:814)
```

**Comment by arnthom** [comment]
bcprov-jdk15on-167.jar should work, if not try bcprov-ext-jdk15on-167.jar, and maybe bcpkix-jdk15on-167.jar is needed too

At https://www.bouncycastle.org/latest_releases.html you can read
> From release 1.40 some implementations of encryption algorithms were removed from the regular jar files at the request of a number of users. Jars with names of the form *-ext-* still include these (at the moment the list is: NTRU).

It may depend on the things you'd like to do, which jar is needed and any documentation of OpenPDF may be incorrect, when BouncyCastle changes the content and naming of jar files ... 
At least it is mentioned on https://github.com/LibrePDF/OpenPDF

> Optional:
    BouncyCastle (BouncyCastle is used to sign PDF files, so it's a recommended dependency)
        - Provider
        - PKIX/CMS

by the way: maybe this is quite like bigos: a little bit of this and a little bit of that and the result is delicious ;)

**Comment by bigos** [comment]
Thank you very much. The suggested version works.

Thank you for noticing that bigos is a delicious dish and not accusing me of being a big-headed author of bigOS. :-)

**Comment by asturio** [comment]
Does this PR #468 solve this issue? I added a link to the pom.xml so the correct version can be verified, and added also what concrete artifact is needed (as of @arnthom)
