### ISSUE TITLE
For Android support Java 8 

### ISSUE THREAD

**Issue by lzqwebsoft** [LibrePDF/OpenPDF#480]
When I use the latest version of OpenFDF(1.3.24) in Android 5.0 to generate PDF, caused an exception:
```
Caused by: java.lang.NoSuchMethodError: No virtual method chars()Ljava/util/stream/IntStream; in class Ljava/lang/String; or its super classes (declaration of 'java.lang.String' appears in /system/framework/core-libart.jar)
	at com.lowagie.text.pdf.PdfChunk.<init>(PdfChunk.java:213)
	at com.lowagie.text.pdf.ColumnText.addWaitingPhrase(ColumnText.java:351)
	at com.lowagie.text.pdf.ColumnText.go(ColumnText.java:810)
	at com.lowagie.text.pdf.PdfPCell.getMaxHeight(PdfPCell.java:996)
	at com.lowagie.text.pdf.PdfPRow.calculateHeights(PdfPRow.java:189)
	at com.lowagie.text.pdf.PdfPRow.getMaxHeights(PdfPRow.java:544)
	at com.lowagie.text.pdf.PdfPTable.getRowHeight(PdfPTable.java:865)
	at com.lowagie.text.pdf.PdfPTable.calculateHeights(PdfPTable.java:418)
	at com.lowagie.text.pdf.PdfPTable.setTotalWidth(PdfPTable.java:359)
	at com.lowagie.text.pdf.PdfDocument.fitsPage(PdfDocument.java:2553)
	at com.lowagie.text.pdf.PdfDocument.addPTable(PdfDocument.java:2507)
	at com.lowagie.text.pdf.PdfDocument.add(PdfDocument.java:683)
	at com.lowagie.text.Document.add(Document.java:302)
```
That means `java.lang.String#chars()` stream method not support in android 5.0 core. that since java 1.8.

I check source code at `PDFChunk.java`:

![PdfChunk](https://user-images.githubusercontent.com/1137657/106260325-40953b80-625b-11eb-9ef8-1bb2d0b4130e.png)

That modify at 2020/05/25 by @grenouille62:

![PdfChunk commit](https://user-images.githubusercontent.com/1137657/106260784-be594700-625b-11eb-964a-b41b9db1fb8b.png)

![PdfChunk commit code](https://user-images.githubusercontent.com/1137657/106261027-0d9f7780-625c-11eb-95f0-5995333799df.png)

To solve this problem, I downgraded to version 1.3.14。

So, guy, Is there has better way to be compatible with java 8 at lower versions of android. Thanks very much.

Last apologize for my bad english。

**Comment by lzqwebsoft** [comment]
Explanation, I change `build.gradle` like this: https://developer.android.com/studio/write/java8-support

Also not support `java.lang.String#chars()`。

**Comment by asturio** [comment]
Hi, I don't know if this is feasible, because OpenPDF is written for Java 8.

There is still a java7 branch, that could be used with ancient versions of android. But the branch is not really maintained (pull request are welcome there :-) ).

I don't think we can solve this in OpenPDF.
