### ISSUE TITLE
ArrayIndexOutOfBoundsException when opening PDF file with invalid indirect reference

### ISSUE THREAD

**Issue by liefke** [LibrePDF/OpenPDF#718]
I have a (confidential) PDF file, which can be opened by Acrobat Reader, Chrome and Firefox, but throws the following exception when opened with OpenPDF:

```
java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:422)
	at java.util.ArrayList.get(ArrayList.java:435)
	at com.lowagie.text.pdf.PdfReader.removeUnusedNode(PdfReader.java:3240)
	at com.lowagie.text.pdf.PdfReader.removeUnusedObjects(PdfReader.java:3285)
	at com.lowagie.text.pdf.PdfReader.readPdf(PdfReader.java:629)
	at com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:280)
	at com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:293)
```

Apparently an _indirect reference_ in the PDF references a _-1_ (which is not valid according to the standard, but is ignored by most readers). I debugged the PDF and there is indeed a "-1 0 R" in one of the dictionary arrays, so no error in the `PRTokeniser`.

iText has fixed that a while ago, see here:
https://stackoverflow.com/questions/16699709/itext-throws-java-lang-arrayindexoutofboundsexception-on-creation-of-pdfreader

**To Reproduce**
Unfortunately I can't provide the PDF file here.

**Expected behavior**
Either throw an InvalidPdfException or (IMHO better) silently drop the invalid and unused reference.

**Version**
- OpenPDF 1.3.27

**Comment by liefke** [comment]
My PDF was created with Microsoft PowerPoint 2019 three weeks ago (2022-04-07). But as it was the first time that such an error was reported and as we have enough other documents that were created by Microsoft PowerPoint 2019 before, one could guess that a Microsoft update is responsible for the broken PDFs (and one could hope, that Microsoft will fix that soon, too).

**Comment by andreasrosdal** [comment]
I get the same problem. I hope that the pull request for this bug can be accepted.

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 7770
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:458)
	at com.lowagie.text.pdf.PdfReader.removeUnusedNode(PdfReader.java:3240)
	at com.lowagie.text.pdf.PdfReader.removeUnusedObjects(PdfReader.java:3285)
	at com.lowagie.text.pdf.PdfReader.readPdf(PdfReader.java:629)
	at com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:212)
	at com.lowagie.text.pdf.PdfReader.<init>(PdfReader.java:196)
	at no.tripletex.pdf.PdfDocument.split(PdfDocument.java:69)
