### ISSUE TITLE
NullpointerException on this.OCGRadioGroup

### ISSUE THREAD

**Issue by koenvb** [LibrePDF/OpenPDF#727]
**Describe the bug**

When trying to call the stamper.getPdfLayers() you get a nullpointer exception

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "com.lowagie.text.pdf.PdfArray.size()" because "this.OCGRadioGroup" is null
    at com.lowagie.text.pdf.PdfWriter.fillOCProperties(PdfWriter.java:2553)
    at com.lowagie.text.pdf.PdfStamperImp.close(PdfStamperImp.java:196)
    at com.lowagie.text.pdf.PdfStamper.close(PdfStamper.java:246)
    at Main.main(Main.java:68)
```

**To Reproduce**

```
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfLayer;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfStamper;
import com.lowagie.text.ExceptionConverter;
import com.lowagie.text.pdf.PdfAnnotation;
import com.lowagie.text.pdf.PdfAppearance;

/**
 * This example was written by Bruno Lowagie. It is part of the book 'iText in
 * Action' by Manning Publications.
 * ISBN: 1932394796
 * http://www.1t3xt.com/docs/book.php
 * http://www.manning.com/lowagie/
 */

public class Main {

  public static void main(String[] args) {
    System.out.println("-> Creates a PDF with optional content.");
    System.out.println("-> jars needed: OpenPDF.jar");
    System.out.println("-> file generated: test_layers.pdf");
    Document document = new Document();
    try {
      PdfWriter writer = PdfWriter.getInstance(document,
          new FileOutputStream("test_layers.pdf"));
      writer.setPdfVersion(PdfWriter.VERSION_1_5);
      document.open();
      PdfLayer layer = new PdfLayer("Do you seeme?", writer);

      BaseFont bf = BaseFont.createFont(BaseFont.HELVETICA,
          BaseFont.WINANSI, BaseFont.NOT_EMBEDDED);
      PdfContentByte cb = writer.getDirectContent();
      cb.beginText();
      cb.setTextMatrix(50, 790);
      cb.setLeading(24);
      cb.setFontAndSize(bf, 18);
      cb.showText("Do you see me?");
      cb.beginLayer(layer);
      cb.newlineShowText("Peek-a-Boo!!!");
      cb.endLayer();
      cb.endText();
      cb.sanityCheck();
      document.close();

    } catch (DocumentException de) {
      System.err.println(de.getMessage());
    } catch (IOException ioe) {
      System.err.println(ioe.getMessage());
    }

    try {
      PdfReader reader;
      PdfStamper stamper;
      reader = new PdfReader("test_layers.pdf");
      stamper = new PdfStamper(reader, new FileOutputStream("test_layers_disabled.pdf"));
      System.out.println(stamper.getPdfLayers());
      stamper.close();
    } catch (IOException e) {
      e.printStackTrace();
    }

  }
}

```

**Expected behavior**
No nullpointer exception

**Screenshots**

**System (please complete the following information):**
 - Used Font:

**Additional context**

Can be solved by adding a null check on this. 
Found the inspiration on this commit for the CSharp library

https://github.com/VahidN/iTextSharp.LGPLv2.Core/pull/43/commits/eb7777b47e8ae31f2939f37520baa7d6f2515a39

**Comment by koenvb** [comment]
I am creating a pull request for this
