### ISSUE TITLE
throw ArrayIndexOutOfBoundsException when Document.add(new Paragraph())

### ISSUE THREAD

**Issue by gaojing5** [LibrePDF/OpenPDF#858]
this is my code:   
=================================================================
 /**
     * 在制定位置添加文本
     *
     * @param doc 文档对象
     * @param data 数据
     * @param documentName 文档名
     * @param imageFilePath 图片位置
     * @param height 封面文字上方留白高度
     * @throws IOException IOException
     */
    public void addRecover(Document doc, List<String> data, String documentName,
        String imageFilePath, int height) throws IOException {
        if (BASE_FONT == null) {
            return;
        }

        Font textFont = new Font(BASE_FONT, PdfReportCover.DATA_SIZE, Font.NORMAL);
        Font titleTextFont = new Font(BASE_FONT, PdfReportCover.DOC_NAME_SIZE, Font.NORMAL);
        doc.newPage();
        PdfReportCover.Builder builderLast = new PdfReportCover.Builder(this.writer, imageFilePath);
        builderLast.build().addBackGroundImage();

        for (int i = 0; i < height; i++) {
            doc.add(new Paragraph(PdfReportCover.DEFAULT_LEADING, " ", textFont));
        }
        for (int i = 0; i< data.size(); ++i) {
            doc.add(new Paragraph(PdfReportCover.DATA_TEXT_LEADING, data.get(i), textFont));
        }
        doc.add(new Paragraph(PdfReportCover.DOC_NAME_LEADING, " ", titleTextFont));
        doc.add(new Paragraph(PdfReportCover.DOC_NAME_LEADING, documentName, titleTextFont));
        doc.newPage();
    }

===============================================================

when run to the last 'doc.add()', there  throw ArrayIndexOutOfBoundsException;

2022-12-17 17:18:45,546 ERROR [pool-22-thread-2][ROOT][com.huawei.neteco.smartpvms.ext.module.intellidiag.business.handler.report.ExportReportTaskHandler 127] executeExportTask failed, waitingTask id = 39, name = GJTest-直连-发邮件_投资收益估算报告_1671268720936 com.lowagie.text.DocumentException: java.lang.ArrayIndexOutOfBoundsException: -1
... 	at com.lowagie.text.pdf.PdfDocument.add(PdfDocument.java:781)
... 	at com.lowagie.text.Document.add(Document.java:302)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.util.report.PdfReportCover.addRecover(PdfReportCover.java:224)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.util.report.PdfReportCover.addRecover(PdfReportCover.java:192)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.util.report.InvestReport.addFirstPage(InvestReport.java:864)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.util.report.InvestReport.makeInvestFile(InvestReport.java:240)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.util.report.InvestReport.generateInvestFile(InvestReport.java:185)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.business.impl.IvCurvesBusinessImpl.lambda$getIvInvestReport$2(IvCurvesBusinessImpl.java:158)
... 	at java.util.ArrayList.forEach(ArrayList.java:1259)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.business.impl.IvCurvesBusinessImpl.getIvInvestReport(IvCurvesBusinessImpl.java:142)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.business.impl.IvCurvesBusinessImpl.exportIvInvestReport(IvCurvesBusinessImpl.java:98)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.business.handler.report.ExportReportTaskHandler.generalRoiEstimationReport(ExportReportTaskHandler.java:227)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.business.handler.report.ExportReportTaskHandler.exportReport(ExportReportTaskHandler.java:211)
... 	at com.huawei.neteco.smartpvms.ext.module.intellidiag.business.handler.report.ExportReportTaskHandler.executeExportTask(ExportReportTaskHandler.java:125)
... 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
... 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
... 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
... 	at java.lang.reflect.Method.invoke(Method.java:498)
... 	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
... 	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
... 	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:95)
... 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
... 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
... 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
... 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
... 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
... 	at java.lang.Thread.run(Thread.java:750)
... Caused by: java.lang.ArrayIndexOutOfBoundsException: -1
... 	at java.util.ArrayList.elementData(ArrayList.java:424)
... 	at java.util.ArrayList.remove(ArrayList.java:501)
... 	at com.lowagie.text.HeaderFooter.paragraph(HeaderFooter.java:274)
... 	at com.lowagie.text.pdf.PdfDocument.doFooter(PdfDocument.java:3233)
... 	at com.lowagie.text.pdf.PdfDocument.initPage(PdfDocument.java:1224)
... 	at com.lowagie.text.pdf.PdfDocument.newPage(PdfDocument.java:1018)
... 	at com.lowagie.text.pdf.PdfDocument.carriageReturn(PdfDocument.java:1295)
... 	at com.lowagie.text.pdf.PdfDocument.add(PdfDocument.java:558)
... 	... 27 more

================================================================
**This issues appeared only in  openpdf-1.3.29.jar, and  openpdf-1.3.20.jar and openpdf-1.3.30.jar is OK.**

**Comment by gaojing5** [comment]
Maybe it is a bug, and has fixed in  : https://github.com/LibrePDF/OpenPDF/pull/813
and I got workaround.  thx~
