### ISSUE TITLE
Unable to add Group3/Group4 TIFFs into Version 1.2.0

### ISSUE THREAD

**Issue by jsorah** [LibrePDF/OpenPDF#91]
Hello, when trying to add a Group3 or Group4 TIFF image into a PDF in release 1.2.0, there is an exception thrown by the underlying sanselan library for "unknown compression":

```
ExceptionConverter: org.apache.sanselan.ImageReadException: Tiff: unknown compression: 4

	at org.apache.sanselan.formats.tiff.datareaders.DataReader.decompress(DataReader.java:135)
	at org.apache.sanselan.formats.tiff.datareaders.DataReaderStrips.readImageData(DataReaderStrips.java:96)
	at org.apache.sanselan.formats.tiff.TiffImageParser.getBufferedImage(TiffImageParser.java:505)
	at org.apache.sanselan.formats.tiff.TiffDirectory.getTiffImage(TiffDirectory.java:163)
	at org.apache.sanselan.formats.tiff.TiffImageParser.getBufferedImage(TiffImageParser.java:441)
	at com.lowagie.text.ImageLoader.getTiffImage(ImageLoader.java:163)
	at com.lowagie.text.Image.getInstance(Image.java:363)
```

This was working previously in version 1.0.5, I presume because the method by which TIFFs were read has changed. 

My initial research indicates that Group3/Group4 support was added to some later version of the sanselan/commons-imaging project, but unsure of how stable these releases are.

**Comment by andreasrosdal** [comment]
Yes, the reason for this is that images are now read by Apache Sanselan (Commons Imaging).

Can you please try using the latest SNAPSHOT version of Commons Imaging instead of the 0.97-incubator version?  More info here:  https://commons.apache.org/proper/commons-imaging/

Please let me know if that solved your problem.

Using a software library instead of maintaining our own image codec should be a good thing.

**Comment by andreasrosdal** [comment]
I have been able to reproduce this problem with loading .TIFF files with group 3/4, with Apache Sanselan version 0.97-incubator.

I have tested Apache Commons Imaging version 1.0-SNAPSHOT, and that was fortunately able to load a .TIFF image with Group 3 correctly. So in time, this will work correctly, once Apache Commons Imaging has a proper maven release to the public maven repo.

I have updated the master branch of OpenPDF to use Apache Commons Imaging version 1.0-SNAPSHOT.

@jsorah Can you perhaps please try the latest master branch and see if that works correctly? 
Do you have any suggestions about how to improve this? The old method of loading .tiff files had to be removed, and this project must use a software library to load .tiff files from now on.

**Comment by jsorah** [comment]
@andreasrosdal I pulled the latest master version and ran it on my code and it is working correctly now.

Unfortunately I do not have many suggestions on how to improve this - it certainly makes the most sense to offload this piece to another project.  I think the downside is that commons-imaging has been "in progress" for many years at this point.

Thanks for looking at this so quickly, I just wanted to note the issue and not so much make you feel like you had to fix it :-).
